version: '{build}'
branches:
  only:
  - master
image:
- Visual Studio 2013
- Visual Studio 2015
- Ubuntu
configuration:
- Release
platform:
- x64
environment:
  matrix:
  - arch: Win64
for:
  -
    matrix:
      only:
        -image: Ubuntu
    clone_folder: /projects/bfa
matrix:
  fast_finish: true

install:
#- ps: C:/projects/bfa/build_files/build_environment/windows/install_cuda.cmd
- sh: cmake cmake-curses-gui

# skip unsupported combinations
init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013%arch%" )
- echo %generator%

#    call build_files/build_environment/windows/install_cuda.cmd
before_build:
- cmd: |-
    cd ..
    if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" (svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/win64_vc12 lib/win64_vc12)
    if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" (svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/win64_vc14 lib/win64_vc14)
    cd bfa
    mkdir build
    cd build
    cmake --version
    cmake .. -G %generator%
build:
  project: c:\projects\bfa\build\Bforartists.sln
  verbosity: minimal
  parallel: true

after_build:
- ps:  7z a bfa_windows.zip c:\projects\bfa\build\bin\*

deploy:
  release: bforartists-git
  description: 'The current git version of Bforartists'
  provider: GitHub
  auth_token:
    secure: lsXb3GHJtJFQ6r6uum7jHYUBK6RWHGA+EjJX+9Jij505T7mO9JCieuOUXPYINdg/
  draft: false
  prerelease: false
  artifact: bfa_windows.zip
  on:
    branch: linux_build
    appveyor_repo_tag: false
#  folder:
